default_stages: [commit, push]
repos:
  - repo: https://github.com/Turnyanskiy/cif-cli.git
    rev: v0.1.0
    hooks:
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: black